name: Build Shared Libraries - Android

env:
  ANDROID_API_VERSION: 35

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            platform: mobile
            targets: "android"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Get Rclone dependencies
        run: go get github.com/rclone/rclone/librclone/gomobile

      - name: Build Rclone Android library
        if: matrix.platform == 'mobile' && contains(matrix.targets, 'android')
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

          # Build Android library
          gomobile bind -target=android \
            -javapkg="org.rclone" \
            -androidapi=${{ env.ANDROID_API_VERSION }} \
            -o=librclone.aar \
            github.com/rclone/rclone/librclone/gomobile

      - name: Upload mobile libraries to SFTP
        if: matrix.platform == 'mobile'
        env:
          SFTP_HOST: ${{ secrets.DEV_SFTP_HOST }}
          SFTP_USER: ${{ secrets.DEV_SFTP_USER }}
          SFTP_PASSWORD: ${{ secrets.DEV_SFTP_PASSWORD }}
          SFTP_PATH: /uploads/rclone/
        run: |
          sudo apt-get update
          sudo apt-get install sshpass -y

          sshpass -p "$SFTP_PASSWORD" sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SFTP_USER@$SFTP_HOST << EOF
          cd $SFTP_PATH
          put librclone.aar
          bye
          EOF
